module.exports = {
  'test1': `<div><p>Hello</p><p>hope this works</p></div>`,
  'test2' : 'excellent',
  'menuProjects': `Learn more about Hugh Lobel's professional projects.`,
  'menuAbout': `This page contains Hugh Lobel's professional biography.`,
  'menuResume': `Read Hugh Lobel's developer resume. Includes a concise overview with annotations.`,
  'menuCV': `Read Hugh Lobel's Artist CV. Contains an in-depth review of his history as a music educator, composer, and performer.`,
  'menuContact': `Hugh Lobel is eager to hear from you. Reach out and we can begin a conversation!`,
  'welcome' : `<h1>Hugh Lobel</h1><h3>Developer, Educator</h3><button class="button-transparent openModal"><span>Contact</span></button>`,
  'projectsPage' : `<p>On this page you can scroll through a list of projects that I've created. Hover over any individual project to learn more.</p>`,
  "MSDP 2" : "<p>The Music and Sound Design Platform (MSDP) is a free and open-source platform for Multimedia Synthesis, Design, and Performance. The tools included in this software provide everything you need to make audio and video creations that are complex, exciting and exploratory, and gives you an interface designed for the stage – whether that stage is a concert hall, a bar, or a bedroom. MSDP is easy to get into – you’ll be making exciting sonic and visual exlorations in seconds – and the software is a thrill to master with an absolute wealth of possibilities for what you can create. We’ve got a getting started video series alongside more involved tutorials on YouTube that will guide you through the use of the software, and an online manual with plenty of information to help you dig deeper.</p><p>Built around a paradigm that emulates the non-linear design of guitar pedal boards, MSDP includes over 100 modules that can be mixed and matched in any combination across any number of boards. MSDP 2.0 features 61 Audio tools, 24 Video tools, and 17 Data tools, each of which is designed to communicate with the others. Beautiful and powerful instruments can be dropped in next to audio file manipulators and wild signal-processing effects. Video synthesis and web cam feeds can be fed through filters and can easily be controlled with audio signals or your favorite MIDI controller. Video and Audio modules can sit side-by-side and can interact with each other in exciting and dynamic ways! MSDP is an ideal platform for experimental multimedia and intermedia artists, VJs, laptop musicians and orchestras, electroacoustic composers, musicians looking for new sonic possibilities for their instruments, and anyone interested in blurring the lines between traditional modes of art making and new, forward-looking creative spaces.</p>",
  "replMax" : "<p>replMax aims to wed the robust multimedia toolkit available in Cycling ’74’s Max 8 with the dynamic fun of a live-coding environment. replMax takes inspiration from popular live-coding languages like SuperCollider and Sonic Pi, but uses modern Javascript and Node.js as it’s foundational languages.<br /></p><p>In replMax you may write and execute any modern Javascript or Node.js code, but we also provide a special Max class to expedite the process of creating and mutating Max objects. The end result is a deep and engaging live-coding multimedia environment that is easy to learn and fun to execute!<br /></p><p>As an additional bonus for Ableton Live 10 suite owners, replMax works equally well as a Max4Live device, and the package includes a template file for both an m4l audio effect and m4l instrument. This makes it extremely simple to live code Max inside of an Ableton Live 10 project.</p>",
};